services:
  drone-course-control:
    image: drone-course-control:latest
    build:
      context: ..
      dockerfile: control/Dockerfile
    # shm_size: '2gb'
    container_name: project_drone_course_control
    # hostname: drone-course-control-dev
    privileged: true
    working_dir: /root/project_drone_course/control
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=1
      - DISPLAY=$DISPLAY
    # ports:
    #   - "5901:5901" # VNC server
    volumes:
      - ./python_interface:/root/project_drone_course/control/python_interface
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # X11
      - ~/.Xauthority:/root/.Xauthority
    network_mode: host
    command: bash -c "tail -f /dev/null"
    # stdin_open: true
    # tty: true
    # restart: unless-stopped
    # # Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: 8G
