/**:
  # Global Parameters
  ros__parameters:
    tf_timeout_threshold: 0.5

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      simulation:
        update_freq: 1000.0  # Hz (default: 1000.0)
        control_freq: 100.0  # Hz (default: 100.0)
        inertial_odometry_freq: 100.0  # Hz (default: 1000.0)
      use_odom_for_control: false  # Use odometry for control instead of ground truth (default: false)
      cmd_freq: 100.0  # Hz (default: 100.0)
      info_freq: 10.0  # Hz (default: 10.0)
      global_ref_frame: "earth"  # (default: earth)
      odom_frame: "odom"  # (default: odom)
      base_frame: "base_link"  # (default: base_link)
      imu_pub_freq: 100.0  # Hz (default: 100.0)
      odometry_pub_freq: 100.0  # Hz (default: 100.0)
      ground_truth_pub_freq: 100.0  # Hz (default: 60.0)
      gps_pub_freq: 1.0  # Hz (default: 60.0)
      gimbal:
        pub_freq: 0.0  # Hz (default: 1.0)
      multirotor:
        imu.accel_noise_var: 0.000001  # (default: 0.0005)
        imu.gyro_noise_var: 0.00003  # (default: 0.003)

  # Motion Controller
  controller_manager:
    ros__parameters:
      use_bypass: true  # Bypass the controller and send direct commands to the platform (default: false)
      cmd_freq: 100.0 # Hz of controller commands send

  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: takeoff_plugin_position
  LandBehavior:
    ros__parameters:
      land_plugin_name: land_plugin_speed
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: go_to_plugin_position
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: follow_path_plugin_position